config/routes.rb
MyFridge::Application.routes.draw do

  resources :user_memory_scores

  resources :comments

  resources :pictures

  resources :invitations

  match '/users/home', to: 'users#home', via: :get

  resources :memories

  resources :circle_users

  resources :circles

  match '/results', to: 'results#mainresults', via: [:get, :post]

  resources :settings

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users, only: [:index, :show]

   

  root to: 'users#home'
  

 

 

  resources :types

  resources :recipes

end

app/models/circle.rb
class Circle < ActiveRecord::Base
  belongs_to :user
  has_many :circle_users, dependent: :destroy
  has_many :users, through: :circle_users 
  has_many :invitations, as: :invitable
  has_many :memories
  has_one :setting
  accepts_nested_attributes_for :setting


 
  validates :user_id, presence: true
  validates :name, uniqueness: true

  searchable do
    text :name, :description
  end
end

app/models/circle_user.rb
class CircleUser < ActiveRecord::Base
  belongs_to :circle
  belongs_to :user

  validates :circle_id, uniqueness: { scope: :user_id }


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :memory

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :invitable, polymorphic: true
  belongs_to :user

  validates :receiving_user_id, uniqueness: { scope: :invitable_id }
  
  def sending_user
    user = User.find_by_id(sending_user_id)
  end

end

app/models/memory.rb
class Memory < ActiveRecord::Base
  scope :reversed, -> { order 'created_at DESC' }
  has_one :picture
  accepts_nested_attributes_for :picture
  has_many :comments
  has_many :user_memory_scores  

  belongs_to :memorable, polymorphic: true
  belongs_to :circle

  def blacked_out?
    memory = Memory.find_by_id(id)
    if memory.blackout_post? and Time.now - memory.timeposted > 60
      true
    else
      false
    end
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true
  belongs_to :memory

  mount_uploader :picture, PictureUploader
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  belongs_to :circle

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :login
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :invitations
  has_many :ingredients, :through => :fridge_ingredients
  has_many :fridge_ingredients
  has_many :recipes
  has_many :circles, dependent: :destroy
  has_many :circles, through: :circle_users 
  belongs_to :recipe_looper
  has_many :circle_users
  mount_uploader :profilePicture, ProfilePictureUploader

  validates :username,
  :uniqueness => {
    :case_sensitive => false
  }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :omniauthable, :omniauth_providers => [:facebook]
  
  # Solr_Sunspot Code:

  searchable do
    text :username
  end
     



  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(name:auth.extra.raw_info.name,
                         provider:auth.provider,
                         uid:auth.uid,
                         email:auth.info.email,
                         password:Devise.friendly_token[0,20]
                         )
    end
    user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions).first
      end
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: [:show, :edit, :update, :destroy]

  # GET /settings
  def index
    @settings = Setting.all
  end

  # GET /settings/1
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings
  def create
    @setting = Setting.new(setting_params)

    if @setting.save
      redirect_to @setting, notice: 'Setting was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /settings/1
  def update
    if @setting.update(setting_params)
      redirect_to @setting, notice: 'Setting was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /settings/1
  def destroy
    @setting.destroy
    redirect_to settings_url, notice: 'Setting was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def setting_params
      params.require(:setting).permit(:circle_id, :type, :invite_only, :show_members)
    end
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/circles_helper.rb
module CirclesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/fridge_helper.rb
module FridgeHelper
end

app/helpers/memories_helper.rb
module MemoriesHelper
end

app/helpers/moods_helper.rb
module MoodsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/settings/_form.html.erb
<%= form_for(@setting) do |f| %>
  <% if @setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
      <% @setting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :circle_id %><br>
    <%= f.number_field :circle_id %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :invite_only %><br>
    <%= f.check_box :invite_only %>
  </div>
  <div class="field">
    <%= f.label :show_members %><br>
    <%= f.check_box :show_members %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/settings/edit.html.erb
<h1>Editing setting</h1>

<%= render 'form' %>

<%= link_to 'Show', @setting %> |
<%= link_to 'Back', settings_path %>

app/views/settings/index.html.erb
<h1>Listing settings</h1>

<table>
  <thead>
    <tr>
      <th>Circle</th>
      <th>Type</th>
      <th>Invite only</th>
      <th>Show members</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= setting.circle_id %></td>
        <td><%= setting.type %></td>
        <td><%= setting.invite_only %></td>
        <td><%= setting.show_members %></td>
        <td><%= link_to 'Show', setting %></td>
        <td><%= link_to 'Edit', edit_setting_path(setting) %></td>
        <td><%= link_to 'Destroy', setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Setting', new_setting_path %>

app/views/settings/new.html.erb
<h1>New setting</h1>

<%= render 'form' %>

<%= link_to 'Back', settings_path %>

app/views/settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Circle:</strong>
  <%= @setting.circle_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @setting.type %>
</p>

<p>
  <strong>Invite only:</strong>
  <%= @setting.invite_only %>
</p>

<p>
  <strong>Show members:</strong>
  <%= @setting.show_members %>
</p>

<%= link_to 'Edit', edit_setting_path(@setting) %> |
<%= link_to 'Back', settings_path %>