config/routes.rb
MyFridge::Application.routes.draw do

  resources :user_memory_scores

  resources :comments

  resources :pictures

  resources :invitations

  match '/users/home', to: 'users#home', via: :get

  resources :memories

  resources :circle_users

  resources :circles

  match '/results', to: 'results#mainresults', via: [:get, :post]

  resources :settings

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users, only: [:index, :show]

   

  root to: 'users#home'
  

 

 

  resources :types

  resources :recipes

end

app/models/circle.rb
class Circle < ActiveRecord::Base
  belongs_to :user
  has_many :circle_users, dependent: :destroy
  has_many :users, through: :circle_users 
  has_many :invitations, as: :invitable
  has_many :memories
  has_one :setting
  accepts_nested_attributes_for :setting


 
  validates :user_id, presence: true
  validates :name, uniqueness: true

  searchable do
    text :name, :description
  end
end

app/models/circle_user.rb
class CircleUser < ActiveRecord::Base
  belongs_to :circle
  belongs_to :user

  validates :circle_id, uniqueness: { scope: :user_id }


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :memory

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :invitable, polymorphic: true
  belongs_to :user

  validates :receiving_user_id, uniqueness: { scope: :invitable_id }
  
  def sending_user
    user = User.find_by_id(sending_user_id)
  end

end

app/models/memory.rb
class Memory < ActiveRecord::Base
  scope :reversed, -> { order 'created_at DESC' }
  has_one :picture
  accepts_nested_attributes_for :picture
  has_many :comments
  has_many :user_memory_scores  

  belongs_to :memorable, polymorphic: true
  belongs_to :circle

  def blacked_out?
    memory = Memory.find_by_id(id)
    if memory.blackout_post? and Time.now - memory.timeposted > 60
      true
    else
      false
    end
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true
  belongs_to :memory

  mount_uploader :picture, PictureUploader
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  belongs_to :circle

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :login
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :invitations
  has_many :ingredients, :through => :fridge_ingredients
  has_many :fridge_ingredients
  has_many :recipes
  has_many :circles, dependent: :destroy
  has_many :circles, through: :circle_users 
  belongs_to :recipe_looper
  has_many :circle_users
  mount_uploader :profilePicture, ProfilePictureUploader

  validates :username,
  :uniqueness => {
    :case_sensitive => false
  }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :omniauthable, :omniauth_providers => [:facebook]
  
  # Solr_Sunspot Code:

  searchable do
    text :username
  end
     



  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(name:auth.extra.raw_info.name,
                         provider:auth.provider,
                         uid:auth.uid,
                         email:auth.info.email,
                         password:Devise.friendly_token[0,20]
                         )
    end
    user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions).first
      end
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :set_invitation, only: [:show, :edit, :update, :destroy]


  # GET /invitations/new
  def new
    @invitation = Invitation.new
  end


  # POST /invitations
  def create
    @invitation = Invitation.new(invitation_params)

    if @invitation.save
      redirect_to @invitation, notice: 'Invitation was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /invitations/1
  def update
    if @invitation.update(invitation_params) and @invitation.accepted?
      CircleUser.create(user_id: @invitation.receiving_user_id, circle_id: @invitation.invitable_id )
      redirect_to Circle.find_by_id(@invitation.invitable_id )
      @invitation.destroy
    else
      redirect_to users_home_path
      @invitation.destroy
    end
  end

  # DELETE /invitations/1
  def destroy
    @invitation.destroy
    redirect_to invitations_url, notice: 'Invitation was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invitation
      @invitation = Invitation.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def invitation_params
      params.require(:invitation).permit(:sending_user_id, :receiving_user_id, :invitable_id, :invitable_type, :time_sent, :accepted)
    end
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/circles_helper.rb
module CirclesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/fridge_helper.rb
module FridgeHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/memories_helper.rb
module MemoriesHelper
end

app/helpers/moods_helper.rb
module MoodsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/invitations/_form.html.erb
<%= form_for(@invitation) do |f| %>
  <% if @invitation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invitation.errors.count, "error") %> prohibited this invitation from being saved:</h2>

      <ul>
      <% @invitation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sending_user_id %><br>
    <%= f.number_field :sending_user_id %>
  </div>
  <div class="field">
    <%= f.label :receiving_user_id %><br>
    <%= f.number_field :receiving_user_id %>
  </div>
  <div class="field">
    <%= f.label :invitable_id %><br>
    <%= f.number_field :invitable_id %>
  </div>
  <div class="field">
    <%= f.label :invitable_type %><br>
    <%= f.text_field :invitable_type %>
  </div>
  <div class="field">
    <%= f.label :time_sent %><br>
    <%= f.datetime_select :time_sent %>
  </div>
  <div class="field">
    <%= f.label :accepted %><br>
    <%= f.check_box :accepted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invitations/edit.html.erb
<h1>Editing invitation</h1>

<%= render 'form' %>

<%= link_to 'Show', @invitation %> |
<%= link_to 'Back', invitations_path %>

app/views/invitations/index.html.erb
<h1>Listing invitations</h1>

<table>
  <thead>
    <tr>
      <th>Sending user</th>
      <th>Receiving user</th>
      <th>Invitable</th>
      <th>Invitable type</th>
      <th>Time sent</th>
      <th>Accepted</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @invitations.each do |invitation| %>
      <tr>
        <td><%= invitation.sending_user_id %></td>
        <td><%= invitation.receiving_user_id %></td>
        <td><%= invitation.invitable_id %></td>
        <td><%= invitation.invitable_type %></td>
        <td><%= invitation.time_sent %></td>
        <td><%= invitation.accepted %></td>
        <td><%= link_to 'Show', invitation %></td>
        <td><%= link_to 'Edit', edit_invitation_path(invitation) %></td>
        <td><%= link_to 'Destroy', invitation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invitation', new_invitation_path %>

app/views/invitations/new.html.erb
<h1>New invitation</h1>

<%= render 'form' %>

<%= link_to 'Back', invitations_path %>

app/views/invitations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sending user:</strong>
  <%= @invitation.sending_user.email %>
</p>

<p>
  <strong>Accepted:</strong>
  <%= @invitation.accepted %>
</p>

<%= link_to 'Edit', edit_invitation_path(@invitation) %> |
<%= link_to 'Back', invitations_path %>