config/routes.rb
MyFridge::Application.routes.draw do

  resources :user_memory_scores

  resources :comments

  resources :pictures

  resources :invitations

  match '/users/home', to: 'users#home', via: :get

  resources :memories

  resources :circle_users

  resources :circles

  match '/results', to: 'results#mainresults', via: [:get, :post]

  resources :settings

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users, only: [:index, :show]

   

  root to: 'users#home'
  

 

 

  resources :types

  resources :recipes

end

app/models/circle.rb
class Circle < ActiveRecord::Base
  belongs_to :user
  has_many :circle_users, dependent: :destroy
  has_many :users, through: :circle_users 
  has_many :invitations, as: :invitable
  has_many :memories
  has_one :setting
  accepts_nested_attributes_for :setting


 
  validates :user_id, presence: true
  validates :name, uniqueness: true

  searchable do
    text :name, :description
  end
end

app/models/circle_user.rb
class CircleUser < ActiveRecord::Base
  belongs_to :circle
  belongs_to :user

  validates :circle_id, uniqueness: { scope: :user_id }


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :memory

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :invitable, polymorphic: true
  belongs_to :user

  validates :receiving_user_id, uniqueness: { scope: :invitable_id }
  
  def sending_user
    user = User.find_by_id(sending_user_id)
  end

end

app/models/memory.rb
class Memory < ActiveRecord::Base
  scope :reversed, -> { order 'created_at DESC' }
  has_one :picture
  accepts_nested_attributes_for :picture
  has_many :comments
  has_many :user_memory_scores  

  belongs_to :memorable, polymorphic: true
  belongs_to :circle

  def blacked_out?
    memory = Memory.find_by_id(id)
    if memory.blackout_post? and Time.now - memory.timeposted > 60
      true
    else
      false
    end
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true
  belongs_to :memory

  mount_uploader :picture, PictureUploader
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  belongs_to :circle

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :login
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :invitations
  has_many :ingredients, :through => :fridge_ingredients
  has_many :fridge_ingredients
  has_many :recipes
  has_many :circles, dependent: :destroy
  has_many :circles, through: :circle_users 
  belongs_to :recipe_looper
  has_many :circle_users
  mount_uploader :profilePicture, ProfilePictureUploader

  validates :username,
  :uniqueness => {
    :case_sensitive => false
  }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :omniauthable, :omniauth_providers => [:facebook]
  
  # Solr_Sunspot Code:

  searchable do
    text :username
  end
     



  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(name:auth.extra.raw_info.name,
                         provider:auth.provider,
                         uid:auth.uid,
                         email:auth.info.email,
                         password:Devise.friendly_token[0,20]
                         )
    end
    user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions).first
      end
  end
end

app/controllers/memories_controller.rb
class MemoriesController < ApplicationController
  before_action :set_memory, only: [:show, :edit, :update, :destroy]

  # GET /memories/new
  def new
    @memory = Memory.new
  end

  # GET /memories/1/edit
  def edit
  end

  # POST /memories
  def create
    @memory = Memory.new(memory_params)
    @circle = @memory.circle

    if @memory.save
      redirect_to @circle, notice: 'Memory was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /memories/1
  def update
    if @memory.update(memory_params)
      redirect_to @memory, notice: 'Memory was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /memories/1
  def destroy
    @memory.destroy
    redirect_to memories_url, notice: 'Memory was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_memory
      @memory = Memory.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def memory_params
      params.require(:memory).permit(:circle_id, :user_id, :score, :memory, :timeposted, :blackout_post, picture_attributes: [ :picture ] )
    end
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/circles_helper.rb
module CirclesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/fridge_helper.rb
module FridgeHelper
end

app/helpers/memories_helper.rb
module MemoriesHelper
end

app/helpers/moods_helper.rb
module MoodsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/memories/_form.html.erb
<%= form_for(@memory) do |f| %>
  <% if @memory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@memory.errors.count, "error") %> prohibited this memory from being saved:</h2>

      <ul>
      <% @memory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :circle_id %><br>
    <%= f.number_field :circle_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="field">
    <%= f.label :memory %><br>
    <%= f.text_field :memory %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/memories/edit.html.erb
<h1>Editing memory</h1>

<%= render 'form' %>

<%= link_to 'Show', @memory %> |
<%= link_to 'Back', memories_path %>

app/views/memories/index.html.erb
<h1>Listing memories</h1>

<table>
  <thead>
    <tr>
      <th>Circle</th>
      <th>User</th>
      <th>Score</th>
      <th>Memory</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @memories.each do |memory| %>
      <tr>
        <td><%= memory.circle_id %></td>
        <td><%= memory.user_id %></td>
        <td><%= memory.score %></td>
        <td><%= memory.memory %></td>
        <td><%= link_to 'Show', memory %></td>
        <td><%= link_to 'Edit', edit_memory_path(memory) %></td>
        <td><%= link_to 'Destroy', memory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Memory', new_memory_path %>

app/views/memories/new.html.erb
<h1>New memory</h1>

<%= render 'form' %>

<%= link_to 'Back', memories_path %>

app/views/memories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Circle:</strong>
  <%= @memory.circle_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @memory.user_id %>
</p>

<p>
  <strong>Score:</strong>
  <%= @memory.score %>
</p>

<p>
  <strong>Memory:</strong>
  <%= @memory.memory %>
</p>

<%= link_to 'Edit', edit_memory_path(@memory) %> |
<%= link_to 'Back', memories_path %>